apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: greenvy-frontend
  namespace: able-folio-400909
spec:
  template:
    spec:
      containers:
      - image: gcr.io/able-folio-400909/greenvy-frontend
        env:
        - name: REACT_APP_BASEURL
          value: https://api.greenvy.store
        - name: REACT_APP_EMAILJS_SERVICE_ID
          value: service_t9j0qkk
        - name: REACT_APP_EMAILJS_TEMPLATE_ID
          value: template_ibnozre
        - name: REACT_APP_EMAILJS_USER_ID
          value: lDUkHYN4AyCPTu_2y
        - name: RZRPAY_KEYID
          value: rzp_test_yzTRoxfvXoHqcL
        - name: REACT_APP_SECRET_KEY
          value: YmZkMzkzO2lpaDplczpzbjA7c29wYWF0Om9kZXNvY2s=
        - name: REACT_APP_IV
          value: A1B2C3D4E5F60708
